In [2]:
import numpy as np 

In [3]:
array = np.array([1,2,3,4,5,6,7,8,9,10,11,12,13,14,15])

In [4]:
print("vector",array)

vector [ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15]


In [5]:
a=array.reshape(3,5)
print("tow dimansional array :",a)

tow dimansional array : [[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]]


In [6]:
print("shape:",a.shape)

shape: (3, 5)


In [7]:
print("dimension:",a.ndim)

dimension: 2


In [8]:
print("data type:",a.dtype.name)

data type: int32


In [9]:
print("size:",a.size)

size: 15


In [10]:
print("type:",type(a))

type: <class 'numpy.ndarray'>


In [11]:
x=np.array([1,2,3])
y=np.array([4,5,6])
print(x+y)
print(x-y)
print(x**2)

[5 7 9]
[-3 -3 -3]
[1 4 9]


In [12]:
a=np.array([1,2,3])
d=a.copy()
print(d)

[1 2 3]


In [13]:
b=a
c=a
b[0]=5
print(a,b,c)

[5 2 3] [5 2 3] [5 2 3]


In [14]:
a=np.array([1,2,3,4,5,6,7])
print(a[0])
print(a[0:5])

1
[1 2 3 4 5]


In [15]:
reverse_array=a[::-1]
print(reverse_array)

[7 6 5 4 3 2 1]


In [16]:
b=np.array([[1,2,3,4,5],[6,7,8,9,10]])
print(b)
print(b[1,1])
print(b[:,1])
print(b[1,:])
print(b[1,1:4])
print(b[-1,:])
print(b[:,-1])

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
7
[2 7]
[ 6  7  8  9 10]
[7 8 9]
[ 6  7  8  9 10]
[ 5 10]
